#!/usr/bin/perl

	#List of Label to navigate the code:
	#GenLevel - generate level function
	#PreSpiel - beginning of code
	#GenChar - generate mistborn;	
	#KeyPress - Pressing buttons e.t.c
	#PrintWind - Draw window for game

#Var Segment fo Warlord!"

$e_file = "e";
$wid = 25;
$hei = 25;
$fy=0; #Field Y
$fx=0; #Field X
$bc=0; #Bitch Count
$kd=1; #Difficulty Modifyer


#Casts Var Array Segment fo Wizard!
$scasts_c = 8;
@scasts = (); #For 8 Basic Spells

#Ich bin Bydlokoder nicht so Es ist some Comments and label da.

%gc = (); #Game Components
$gc{'x'} = 0;			#X Position	
$gc{'y'} = 0;			#Y Position
$gc{'n'} = "Spieler";		#Name
$gc{'cp'} = 10;			#Cast Power
$gc{'1r'} = 0;			#Darkness resistence 
$gc{'2r'} = 0;			#Light resistence 
$gc{'3r'} = 0;			#Heat resistence 
$gc{'4r'} = 0;			#Frost resistence 
$gc{'5r'} = 0;			#Nature resistence 
$gc{'6r'} = 0;			#Metall resistence 
$gc{'7r'} = 0;			#Air resistence 
$gc{'8r'} = 0;			#Earth resistence 
$gc{'s'} = 'o';			#Symbol	
$gc{'h'} = 36;			#Health	

%field = ();	#Format of Net: field{x;y}


#####################################
#Refresho
sub ref{	
	for ($i = 1; $i <= $bc; $i++)
	{
		$field{$gc{'x' . $i} . ':' . $gc{'y' . $i}} = $gc{'s' . $i};
	}	
	$field{$gc{'x'} . ':' . $gc{'y'}} = $gc{'s'};	
}

#Readfile
sub rsp{
	open(FILE, "$e_file");
	for ($i=1;$i<= $scasts_c; $i++)
	{
		$scasts[$i] = <FILE>;
	}
	close(FILE);
}


#GenChar
sub genc{
	$bc+=1;
	$gc{'n' . $bc} = "Mistborn #$bc";
	$gc{'x' . $bc} = int(rand(23))+2;
	$gc{'y' . $bc} = int(rand(23))+2;
	$gc{'s' . $bc} = 'm';
	$gc{'1r' . $bc} = int(rand(201))-100;
	$gc{'2r' . $bc} = $gc{'1r' . $bc} * -1;
	$gc{'3r' . $bc} = int(rand(201))-100;
	$gc{'4r' . $bc} = $gc{'3r' . $bc} * -1;
	$gc{'5r' . $bc} = int(rand(201))-100;
	$gc{'6r' . $bc} = $gc{'5r' . $bc} * -1;
	$gc{'7r' . $bc} = int(rand(201))-100;
	$gc{'8r' . $bc} = $gc{'7r' . $bc} * -1;
	$gc{'h' . $bc} = (int(rand(11))+10)*$kd;
}

#GenLevel
sub gl{
	$symb = "#";
	for( $i=1; $i<=$wid; $i++)
	{
		for ( $j=1; $j<=$hei;$j++)
		{
			$field{$i . ':' . $j} = "$symb";
		} 
	}
	$symb = " ";
	#Arena Mod
	for( $i=2; $i<$wid; $i++)
	{
		for ( $j=2; $j<$hei;$j++)
		{
			$field{$i . ':' . $j} = "$symb";
		} 
	}
	$gc{'x'} = 13;
	$gc{'y'} = 13;	
}

#Check Colision
sub col{
	$ret = 0;
	for ($i = 1; $i <= $bc; $i++)
	{
		if ( $gc{'x' . $i} == $dx && $gc{'y' . $i} == $dy && $gc{'h' . $i} > 0){
			$ret = 1;
		} 
	}
	if ($field{$dx . ':' . $dy} eq "#") {
		$ret = 1;
	}
	$ret;
}

#KeyPress
sub kp{
	$dx = $gc{'x'};
	$dy = $gc{'y'};
	$k = <STDIN>;
	if ($k eq "w\n")
	{
		$dy -= 1;
	}	

	if ($k eq "s\n")
	{
		$dy += 1;
	}

	if ($k eq "a\n")
	{
		$dx -= 1;
	}

	if ($k eq "d\n")
	{
		$dx += 1;
	}
	
	if ($k eq "c\n")
	{
		print "Select Spelltarget!\n";
		$curt = 1;
		@icurt = ();
		for ($i = 1; $i <= $bc; $i++)
		{
			if ($gc{'x' . $i} >= $fx
				&& $gc{'x' . $i} <= $fx+6
				&& $gc{'y' . $i} >= $fy
				&& $gc{'y' . $i} <= $fy+6
				&& $gc{'h' . $i} > 0)
			{
				print "$curt)$gc{'n' . $i}\n";
				$icurt[$curt] = $i;
				$curt+=1;
			}
		}
		print "$curt) Cancel and Die Fur Glory of leidenkonung!\n";
		$ans = <STDIN>;
		$target = $icurt[$ans];
		print "Enter Spell to cast it!\n";
		$sp = <STDIN>;
		for ($i = 1; $i <= $scasts_c; $i++)
		{
			if ($scasts[$i] eq $sp)
			{
				$dmg = $gc{'cp'}+ ($gc{'cp'} * $gc{$i . 'r' . $target} / 100);
				$gc{'h' . $target} -= $dmg;
				print "$dmg Damage to Mistvieh!\n";
				if ($gc{'h' . $target} <= 0)
				{
					print "And Mistvieh Has been slain...\n";
					$gc{'s' . $target} = " ";
				}
			}
		}
		$ans = <STDIN>;
	}
	if ($k eq "q\n")
	{
		exit;	
	}
	$x = &col;
	print "$x\n";
	if (&col == 0)
	{
		$field{$gc{'x'} . ':' . $gc{'y'}} = ' ';
		$gc{'x'} = $dx;	
		$gc{'y'} = $dy;
		&ref;
	}
	$fx = $gc{'x'} - 3;
	$fy = $gc{'y'} - 3;
}

sub iprint{
	print "Hero: $gc{'n'}\n";
	print "Ya Health: $gc{'h'}\n";
	print "Ya CastPower: $gc{'cp'}\n";
}

#PrintWind
sub wprint{
	
	&kp;
	system(clear);
	&ref;
	&printmap;
	&iprint;
	&wprint;	
	
}


sub printmap{

	for( $i=1; $i<=$wid; $i++)
	{
		for ( $j=1; $j<=$hei;$j++)
		{
			print "$field{$j . ':' . $i}";
		}
	print "\n"; 
	}
}


#PreSpiel

&rsp;
system(clear);    
&gl;
for ($j=1;$j<10;$j++)
{
	&genc;
}
&ref;
&printmap;
&iprint;
&wprint;



